language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3

sudo: required

services:
  - docker

script:
  - >
    wget -qO- bit.ly/ansibletest | env
    DOCKER_IMAGES="centos:7 debian:7 ubuntu:12.04
    ubuntu:16.04 fedora:20 fedora:24"
    ANSIBLE_VERSIONS="1.4.4 1.8.4 2.0.0.2 2.1.0.0"
    sh

after_failure:
  - cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
