---
- include: compat.yml

#- include: Debian.yml
#  when: ansible_os_family == 'Debian'

- include: epel.yml
  when: ansible_distribution == 'CentOS'

- include_vars: "{{item}}"
  with_first_found:
  - "../vars/{{ansible_distribution}}-{{ansible_distribution_major_version | int}}.yml"
  - "../vars/{{ansible_distribution}}.yml"
  - "../vars/{{ansible_os_family}}.yml"
  - "../vars/default.yml"

- name: install exiftool with default package manager
  action: "{{backcompat_pkg_mgr}} name={{package_name}}"
  sudo: yes
  when: backcompat_pkg_mgr == "yum" or backcompat_pkg_mgr == "apt"

# Use command since dnf was only added as a module in ansible 1.9.0
- name: install exiftool with dnf
  command: dnf install -y {{package_name}}
  register: dnf_result
  changed_when: "'is already installed' in dnf_result.stdout"
  sudo: yes
  when: backcompat_pkg_mgr == "dnf"
